### ISSUE TITLE
Putioarr started erroring out when testing the connection with Sonarr and Radarr

### ISSUE THREAD

**Issue by KPG2000** [wouterdebie/putioarr#13]
*NOTE THAT UNCLEAR BUG REPORTS (i.e. without the information requested below like logs, settings, versions, etc) MIGHT BE CLOSED WITHOUT ANY HELP!!*

Please check https://github.com/wouterdebie/putioarr/releases if any breaking changes have been made before filing a bug report.

**Describe the bug**
When radarr and sonarr try to connect to putioarr it errors out.

**To Reproduce**
1. Have Sonarr/Radarr with an error running and hit test connection
2. See putioarr error out

** Logs **

───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____ 
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____  
      | __  |  |  | |  |  |    \ 
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/ 
  Based on images from linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
[custom-init] No custom files found, skipping...
[2024-12-02T16:16:23Z INFO ] Starting putioarr, version 0.5.19
[2024-12-02T16:16:24Z INFO ] Starting web server at http://0.0.0.0:9091
[2024-12-02T16:16:24Z INFO ] starting 2 workers
[2024-12-02T16:16:24Z INFO ] Actix runtime found; starting in Actix runtime
[2024-12-02T16:16:24Z INFO ] Checking unfinished transfers
Connection to 127.0.0.1 9091 port [tcp/*] succeeded!
[ls.io-init] done.
thread 'actix-rt|system:0|arbiter:0' panicked at src/http/handlers.rs:103:60:
called `Result::unwrap()` on an `Err` value: error decoding response body
Caused by:
    invalid value: integer `-1`, expected u64 at line 1 column 8544
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'actix-rt|system:0|arbiter:1' panicked at src/http/handlers.rs:103:60:
called `Result::unwrap()` on an `Err` value: error decoding response body
Caused by:
    invalid value: integer `-1`, expected u64 at line 1 column 8544
thread 'actix-rt|system:0|arbiter:1' panicked at src/http/handlers.rs:103:60:
called `Result::unwrap()` on an `Err` value: error decoding response body
Caused by:
    invalid value: integer `-1`, expected u64 at line 1 column 8542
thread 'actix-rt|system:0|arbiter:0' panicked at src/http/handlers.rs:103:60:
called `Result::unwrap()` on an `Err` value: error decoding response body
Caused by:
    invalid value: integer `-1`, expected u64 at line 1 column 8543

** Configuration **
#Required. Username and password that sonarr/radarr/whisparr use to connect to the proxy
username = "kpg"
password = "xxxxxxxxxxxxxxxxx"

#Required. Directory where the proxy will download files to. This directory has to be readable by
#sonarr/radarr/whisparr in order to import downloads
download_directory = "/data12/Downloads/"

#Optional bind address, default "0.0.0.0"
bind_address = "0.0.0.0"

#Optional TCP port, default 9091
port = 9091

#Optional log level, default "info"
loglevel = "info"

#Optional UID, default 1000. Change the owner of the downloaded files to this UID. Requires root.
uid = 1000

#Optional polling interval in secs, default 10.
polling_interval = 10

#Optional skip directories when downloding, default ["sample", "extras"]
skip_directories = ["sample", "extras"]

#Optional number of orchestration workers, default 10. Unless there are many changes coming from
#put.io, you shouldn't have to touch this number. 10 is already overkill.
orchestration_workers = 10

#Optional number of download workers, default 4. This controls how many downloads we run in parallel.
download_workers = 4

[putio]
#Required. Putio API key. You can generate one using putioarr get-token
api_key =  "xxxxxxxxxxxxxxxxxxx"

#Both [sonarr] and [radarr] are optional, but you'll need at least one of them
[sonarr]
url = "http://172.20.0.1:8989"
#Can be found in Settings -> General
api_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxx"

[radarr]
url = "http://172.20.0.1:7878"
#qCan be found in Settings -> General
api_key = "xxxxxxxxxxxxxxxxxxxxxxxxx"

**Environment**
Ubuntu 22.04

**Docker**
/data12 is the same folder for Radaar, Sonarr and Putioarr.

**Additional context**
It was working fine until I tried downloading a particular season of a show and it just broke after that. Tried moving the config file to a different folder and even repulling the docker image.

**Comment by wouterdebie** [comment]
Thanks for the bug report. This happens when https://api.put.io/v2/transfers/list is called and some field returns -1 where nothing or an integer >= 0 is expected. I can't seem to reproduce this though. Can you execute a "curl https://api.put.io/v2/transfers/list?oauth_token=<YOUR_PUTIO_API_KEY>" and either send me the results or tell me where the value is -1?

**Comment by eralpkaraduman** [comment]
I fetched `https://api.put.io/v2/transfers/list?oauth_token=<MY_PUTIO_API_KEY>"`
looks like there is `"estimated_time": -1,` for one of the items in the response

such item in response;

```
{
"availability": 78,
"callback_url": "",
"client_ip": null,
"completion_percent": 100,
"created_at": "2025-01-01T20:18:45",
"created_torrent": false,
"current_ratio": 1,
"down_speed": 0,
"download_id": REDACTED,
"downloaded": REDACTED,
"error_message": null,
"estimated_time": -1,
"file_id": REDACTED,
"finished_at": "2025-01-01T20:18:45",
"hash": "REDACTED",
"id": 95819771,
"is_private": false,
"name": "REDACTED",
"peers_connected": 15,
"peers_getting_from_us": 14,
"peers_sending_to_us": 0,
"percent_done": 100,
"save_parent_id": 485793409,
"seconds_seeding": 1758,
"simulated": true,
"size": 6121685917,
"source": "REDACTED",
"started_at": "2025-01-01T20:18:45",
"status": "COMPLETED",
"subscription_id": null,
"torrent_link": null,
"tracker": null,
"tracker_message": null,
"type": "TORRENT",
"up_speed": 2588000,
"uploaded": 6132419733,
"userfile_exists": true
},
```

in putioarr logs;
```
called `Result::unwrap()` on an `Err` value: error decoding response body

Caused by:

    invalid value: integer `-1`, expected u64 at line 1 column 2483

thread 'actix-rt|system:0|arbiter:0' panicked at src/http/handlers.rs:103:60:
```
